version: '3'
services:
  db:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=main
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pgdata: