# Generated by Django 3.0.10 on 2020-09-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='shorturl',
            name='user',
        ),
    ]
