# Generated by Django 3.0.10 on 2020-09-08 20:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200908_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='new_url',
            field=models.CharField(default=main.models.buildstr, max_length=50, unique=True),
        ),
    ]
